terms = """1. All disputes are subject to jurisdiction in Mumbai only. \n2. Payment terms: \n2.a. First 5 orders will be upfront payment.\n2.b. As business and regular orders come through option of 2-4 week Cheque / post-dated cheque (PDC) will be offered.\n2.c. For payments made via NEFT, IMPS, RTGS or cheque's directly deposited, Kindly send us the receipt on our WhatsApp no.+91 9930623544 / +91 9372236448 or info@barkbutler.in.\n2d. Incase of cheque bounce or payment default we will be allowed to take any goods available in your premises to cover our invoice amount, damages, interest rate on defaulted payments (mentioned below), lawyer fees (if involved) and expenses for transportation of goods from your premises to ours. If you, your team members or staff behave rudelyf we will involve the police if required. \n3. Customer will be informed before the PDC is deposited.\n4. On delivery of goods our courier partner will take the authority person's signature on the courier bill. This implies that the goods have been received and accepted by you and the Invoice sent in your package or via whatsapp is now your liability. We wont take a signed copy of the invoice as there will further charges and delay to send it back to us. \n5. Bills not cleared by the due date will attract 24% interest p.a.\n6. Our responsibility shall cease after the goods are handed over to the carrier.\n7. Returns & Replacements \n7.a. On receipt of the order, you have 5 days to lodge any complaint regarding missing/damaged items. 6.b. In case the retailer's customer receives a damaged product the item will be replaced.\n7.c In case the retailer’s customer damages/destroys the products within 3 days, the item will be replaced. Kindly note, returns are only applicable if the right-sized product (as mentioned on the packaging) is sold to the right sized dog. \n8. Items not sold within 8-12 weeks shall be sold via a discount scheme or replaced with better-suited items for that particular retail store.\n9. Logistics charges can be applicable for goods sold and returned.  \n10. A non-negotiable penalty of ₹1000 will be levied for dishonoured cheque"""

GST_STATE_CODES = {
    "01": "JK",
    "02": "HP",
    "03": "PB",
    "04": "CH",
    "05": "UT",
    "06": "HR",
    "07": "DL",
    "08": "RJ",
    "09": "UP",
    "10": "BR",
    "11": "SK",
    "12": "AR",
    "13": "NL",
    "14": "MN",
    "15": "MZ",
    "16": "TR",
    "17": "ML",
    "18": "AS",
    "19": "WB",
    "20": "JH",
    "21": "OR",
    "22": "CT",
    "23": "MP",
    "24": "GJ",
    "25": "DD",
    "26": "DN",
    "27": "MH",
    "28": "AP",
    "29": "KA",
    "30": "GA",
    "31": "LD",
    "32": "KL",
    "33": "TN",
    "34": "PY",
    "35": "AN",
    "36": "TG",
    "37": "AP",
    "38": "LD",
}

STATE_CODES = {
    "Andhra Pradesh": "AD",
    "Arunachal Pradesh": "AR",
    "Assam": "AS",
    "Bihar": "BR",
    "Chhattisgarh": "CG",
    "Goa": "GA",
    "Gujarat": "GJ",
    "Haryana": "HR",
    "Himachal Pradesh": "HP",
    "Jharkhand": "JH",
    "Karnataka": "KA",
    "Kerala": "KL",
    "Madhya Pradesh": "MP",
    "Maharashtra": "MH",
    "Manipur": "MN",
    "Meghalaya": "ML",
    "Mizoram": "MZ",
    "Nagaland": "NL",
    "Odisha": "OD",
    "Punjab": "PB",
    "Rajasthan": "RJ",
    "Sikkim": "SK",
    "Tamil Nadu": "TN",
    "Telangana": "TS",
    "Tripura": "TR",
    "Uttar Pradesh": "UP",
    "Uttarakhand": "UK",
    "West Bengal": "WB",
    "Andaman and Nicobar Islands": "AN",
    "Chandigarh": "CH",
    "Dadra and Nagar Haveli and Daman and Diu": "DD",
    "Delhi": "DL",
    "Jammu and Kashmir": "JK",
    "Ladakh": "LA",
    "Lakshadweep": "LD",
    "Dadra & Nagar Haveli and Daman & Diu": "DN",
    "Puducherry": "PY",
    "Other Territory": "OT",
}
